### ISSUE TITLE
No suck export GetDiscordRoles in resource Badger_Discord_API

### ISSUE THREAD

**Issue by cree01** [Jordan2139/Guardian#3]
Hello, my guardian is update, same for my discord API but i still can't connect to my server and this error still here ... Could you help me ?
![image](https://user-images.githubusercontent.com/35968029/109508317-08725a00-7aa0-11eb-890d-da8cac350134.png)

**Comment by Jordan2139** [comment]
This is not an issue with Guardian, it just simply prints after the Guardian print. Please install Badger_Discord_API correctly
